language: bash

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login cz.d4s.top:9443 -u "$DOCKER_USERNAME" --password-stdin
 
script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
      image_name=${image#*/}
      image_name=${image_name%@*}
      docker pull $image

      docker tag $image cz.d4s.top:9443/gcr.io/$image_name
      docker push cz.d4s.top:9443/gcr.io/$image_name
    done
